/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.hypertrace.config.service;

public class MyServiceImplementation {
    public String getText() {
        return "implementation";
    }
}
